version: '3.7'
services:
  google_calendar_clone_docker:
    image: google_calendar_clone_docker
    container_name: google_calendar_clone_docker
    networks:
      docker_network:
        ipv4_address: 10.5.0.6
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        ENVIRONMENT_BUILD: production
        NODE_VERSION: 20.2.0
        EXPOSE_PORT: 8080
    ports:
      - 8080:8080
    tty: true
    restart: on-failure

networks:
  docker_network:
    external: true
